//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringDatabaseDataDfSOYfAC", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial struct KeyValuePairOfstringDatabaseDataDfSOYfAC : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private WCF.DatabaseData ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF.DatabaseData Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseData", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial class DatabaseData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private int TablesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tables
        {
            get
            {
                return this.TablesField;
            }
            set
            {
                this.TablesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringTableDataDfSOYfAC", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial struct KeyValuePairOfstringTableDataDfSOYfAC : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private WCF.TableData ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF.TableData Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableData", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial class TableData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ColumnsField;
        
        private string NameField;
        
        private int RowsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Columns
        {
            get
            {
                return this.ColumnsField;
            }
            set
            {
                this.ColumnsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringColumnDfSOYfAC", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial struct KeyValuePairOfstringColumnDfSOYfAC : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private WCF.Column ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF.Column Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial class Column : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string TypeField;
        
        private WCF.Value[] ValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF.Value[] Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Value", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    public partial class Value : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceSharedDatabase")]
public interface IServiceSharedDatabase
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateDatabaseResponse")]
    string CreateDatabase(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateDatabaseResponse")]
    System.Threading.Tasks.Task<string> CreateDatabaseAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateTableResponse")]
    string CreateTable(string database, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateTableResponse")]
    System.Threading.Tasks.Task<string> CreateTableAsync(string database, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateTableDistinct", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateTableDistinctResponse")]
    string CreateTableDistinct(string database, string table, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateTableDistinct", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateTableDistinctResponse")]
    System.Threading.Tasks.Task<string> CreateTableDistinctAsync(string database, string table, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateColumn", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateColumnResponse")]
    string CreateColumn(string database, string table, string name, string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateColumn", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateColumnResponse")]
    System.Threading.Tasks.Task<string> CreateColumnAsync(string database, string table, string name, string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateRow", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateRowResponse")]
    void CreateRow(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/CreateRow", ReplyAction="http://tempuri.org/IServiceSharedDatabase/CreateRowResponse")]
    System.Threading.Tasks.Task CreateRowAsync(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/RenameDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/RenameDatabaseResponse")]
    void RenameDatabase(string database, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/RenameDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/RenameDatabaseResponse")]
    System.Threading.Tasks.Task RenameDatabaseAsync(string database, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/RenameTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/RenameTableResponse")]
    void RenameTable(string database, string table, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/RenameTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/RenameTableResponse")]
    System.Threading.Tasks.Task RenameTableAsync(string database, string table, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/SetValue", ReplyAction="http://tempuri.org/IServiceSharedDatabase/SetValueResponse")]
    void SetValue(string database, string table, string column, int row, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/SetValue", ReplyAction="http://tempuri.org/IServiceSharedDatabase/SetValueResponse")]
    System.Threading.Tasks.Task SetValueAsync(string database, string table, string column, int row, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetDatabases", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetDatabasesResponse")]
    WCF.KeyValuePairOfstringDatabaseDataDfSOYfAC[] GetDatabases();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetDatabases", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetDatabasesResponse")]
    System.Threading.Tasks.Task<WCF.KeyValuePairOfstringDatabaseDataDfSOYfAC[]> GetDatabasesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetTables", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetTablesResponse")]
    WCF.KeyValuePairOfstringTableDataDfSOYfAC[] GetTables(string database);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetTables", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetTablesResponse")]
    System.Threading.Tasks.Task<WCF.KeyValuePairOfstringTableDataDfSOYfAC[]> GetTablesAsync(string database);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetColumns", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetColumnsResponse")]
    WCF.KeyValuePairOfstringColumnDfSOYfAC[] GetColumns(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/GetColumns", ReplyAction="http://tempuri.org/IServiceSharedDatabase/GetColumnsResponse")]
    System.Threading.Tasks.Task<WCF.KeyValuePairOfstringColumnDfSOYfAC[]> GetColumnsAsync(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteDatabaseResponse")]
    void DeleteDatabase(string database);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteDatabase", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteDatabaseResponse")]
    System.Threading.Tasks.Task DeleteDatabaseAsync(string database);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteTableResponse")]
    void DeleteTable(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteTable", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteTableResponse")]
    System.Threading.Tasks.Task DeleteTableAsync(string database, string table);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteColumn", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteColumnResponse")]
    void DeleteColumn(string database, string table, string column);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteColumn", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteColumnResponse")]
    System.Threading.Tasks.Task DeleteColumnAsync(string database, string table, string column);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteRow", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteRowResponse")]
    void DeleteRow(string database, string table, int row);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSharedDatabase/DeleteRow", ReplyAction="http://tempuri.org/IServiceSharedDatabase/DeleteRowResponse")]
    System.Threading.Tasks.Task DeleteRowAsync(string database, string table, int row);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceSharedDatabaseChannel : IServiceSharedDatabase, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceSharedDatabaseClient : System.ServiceModel.ClientBase<IServiceSharedDatabase>, IServiceSharedDatabase
{
    
    public ServiceSharedDatabaseClient()
    {
    }
    
    public ServiceSharedDatabaseClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceSharedDatabaseClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceSharedDatabaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceSharedDatabaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string CreateDatabase(string name)
    {
        return base.Channel.CreateDatabase(name);
    }
    
    public System.Threading.Tasks.Task<string> CreateDatabaseAsync(string name)
    {
        return base.Channel.CreateDatabaseAsync(name);
    }
    
    public string CreateTable(string database, string name)
    {
        return base.Channel.CreateTable(database, name);
    }
    
    public System.Threading.Tasks.Task<string> CreateTableAsync(string database, string name)
    {
        return base.Channel.CreateTableAsync(database, name);
    }
    
    public string CreateTableDistinct(string database, string table, string name)
    {
        return base.Channel.CreateTableDistinct(database, table, name);
    }
    
    public System.Threading.Tasks.Task<string> CreateTableDistinctAsync(string database, string table, string name)
    {
        return base.Channel.CreateTableDistinctAsync(database, table, name);
    }
    
    public string CreateColumn(string database, string table, string name, string type)
    {
        return base.Channel.CreateColumn(database, table, name, type);
    }
    
    public System.Threading.Tasks.Task<string> CreateColumnAsync(string database, string table, string name, string type)
    {
        return base.Channel.CreateColumnAsync(database, table, name, type);
    }
    
    public void CreateRow(string database, string table)
    {
        base.Channel.CreateRow(database, table);
    }
    
    public System.Threading.Tasks.Task CreateRowAsync(string database, string table)
    {
        return base.Channel.CreateRowAsync(database, table);
    }
    
    public void RenameDatabase(string database, string name)
    {
        base.Channel.RenameDatabase(database, name);
    }
    
    public System.Threading.Tasks.Task RenameDatabaseAsync(string database, string name)
    {
        return base.Channel.RenameDatabaseAsync(database, name);
    }
    
    public void RenameTable(string database, string table, string name)
    {
        base.Channel.RenameTable(database, table, name);
    }
    
    public System.Threading.Tasks.Task RenameTableAsync(string database, string table, string name)
    {
        return base.Channel.RenameTableAsync(database, table, name);
    }
    
    public void SetValue(string database, string table, string column, int row, string value)
    {
        base.Channel.SetValue(database, table, column, row, value);
    }
    
    public System.Threading.Tasks.Task SetValueAsync(string database, string table, string column, int row, string value)
    {
        return base.Channel.SetValueAsync(database, table, column, row, value);
    }
    
    public WCF.KeyValuePairOfstringDatabaseDataDfSOYfAC[] GetDatabases()
    {
        return base.Channel.GetDatabases();
    }
    
    public System.Threading.Tasks.Task<WCF.KeyValuePairOfstringDatabaseDataDfSOYfAC[]> GetDatabasesAsync()
    {
        return base.Channel.GetDatabasesAsync();
    }
    
    public WCF.KeyValuePairOfstringTableDataDfSOYfAC[] GetTables(string database)
    {
        return base.Channel.GetTables(database);
    }
    
    public System.Threading.Tasks.Task<WCF.KeyValuePairOfstringTableDataDfSOYfAC[]> GetTablesAsync(string database)
    {
        return base.Channel.GetTablesAsync(database);
    }
    
    public WCF.KeyValuePairOfstringColumnDfSOYfAC[] GetColumns(string database, string table)
    {
        return base.Channel.GetColumns(database, table);
    }
    
    public System.Threading.Tasks.Task<WCF.KeyValuePairOfstringColumnDfSOYfAC[]> GetColumnsAsync(string database, string table)
    {
        return base.Channel.GetColumnsAsync(database, table);
    }
    
    public void DeleteDatabase(string database)
    {
        base.Channel.DeleteDatabase(database);
    }
    
    public System.Threading.Tasks.Task DeleteDatabaseAsync(string database)
    {
        return base.Channel.DeleteDatabaseAsync(database);
    }
    
    public void DeleteTable(string database, string table)
    {
        base.Channel.DeleteTable(database, table);
    }
    
    public System.Threading.Tasks.Task DeleteTableAsync(string database, string table)
    {
        return base.Channel.DeleteTableAsync(database, table);
    }
    
    public void DeleteColumn(string database, string table, string column)
    {
        base.Channel.DeleteColumn(database, table, column);
    }
    
    public System.Threading.Tasks.Task DeleteColumnAsync(string database, string table, string column)
    {
        return base.Channel.DeleteColumnAsync(database, table, column);
    }
    
    public void DeleteRow(string database, string table, int row)
    {
        base.Channel.DeleteRow(database, table, row);
    }
    
    public System.Threading.Tasks.Task DeleteRowAsync(string database, string table, int row)
    {
        return base.Channel.DeleteRowAsync(database, table, row);
    }
}
